### PR TITLE
Add CPP preprocessors for Servant 0.12 and 0.13

### PR DESCRIPTION
**Pull request by adelbertc**
Hit these issues when pulling in `hw-kafka-avro` from a (Nix) project depending on Servant 0.12.x. I am unsure if I should do anything in the Stack files to account for this, if so please let me know!

### CODE REVIEW

**Comment by adelbertc** [comment]
It seems CI is failing because of the LTS being used - basically Servant 0.12+ needs `servant-client-core` but that package didn't exist before Servant 0.12. I think the best option might be to just bump the LTS version to something recent that has at least Servant 0.12+, what do you folks think? Also open to other suggestions.

**Comment by AlexeyRaga** [comment]
Sorry for very slow replies, I am travelling now (ZuriHac).
I  am OK to bump LTS version in general, but I still would like it to be working with older LTS... 

I am thinking to give up on Servant because it breaks API often and to use something like `wreq` instead...

**Comment by adelbertc** [comment]
@AlexeyRaga How do you want to proceed? I'm unfamiliar with Stack so I'm not sure how to do cross-builds across different library versions if such a thing is possible. I think I know how we would do it in Nix if you're interested in such a solution.

BTW, I am on the same team as @tikhonjelvis who you've worked with on the Haskell [avro](https://github.com/galoisinc/avro) bindings 😄  - we're looking to use Avro for our serialization needs on our team.

**Comment by AlexeyRaga** [comment]
I think updating CI itself for building for multiple GHCs/LTSs is easy and we already do it in Avro,  so can be copy/pasted:
https://github.com/GaloisInc/avro/blob/master/.circleci/config.yml

Dealing with Servant versions - not sure. Long term solution would be to get rid of Servant and to use something much simpler and stable (`wreq` or even `http-client` directly). If you can do that then it would be awesome, otherwise I can do it when I am back home.

A short-term solution would be to, as you say, just bump LTS and don't worry about compatibility for now. I think we can do it given that you need it to work now, and compatibility can be re-introduced later, but before any significant changes/fixes could be made (and I don't have any in mind).

So it is up to you how to proceed: either replace Servant or let's just bump LTS. I'll accept the PR  anyway when the build is green :)

Thanks for your contribution and pass my greetings to Tikhon! :)

**Comment by AlexeyRaga** [comment]
Just a heads up:
I have a long flight (~14 hours) and I will be working on removing Servant and using `wreq`.

**Comment by adelbertc** [comment]
@AlexeyRaga oof, sorry for the slow response, I've been sick the past couple days 😷 

That sounds good, thank you for doing that! I will wait for that then 😄

**Comment by adelbertc** [comment]
@AlexeyRaga Judging by your recent commits looks like we can close this?

**Comment by AlexeyRaga** [comment]
@adelbertc yes, I think so.

**Pull request closed without merging**
